{% set version = "0.11.0" %}

package:
  name: mccode-antlr
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/mccode_antlr/mccode_antlr-{{ version }}.tar.gz
  sha256: 56015332e593f590e1f802deecfea0a22a2e5618cb0c2d779ccba39b89ae01e7

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - mcstas-antlr = mccode_antlr.cli.commands:mcstas
    - mcxtrace-antlr = mccode_antlr.cli.commands:mcxtrace
    - mcrun-antlr = mccode_antlr.run.runner:mcstas_cmd
    - mxrun-antlr = mccode_antlr.run.runner:mcxtrace_cmd
    - mccode-antlr = mccode_antlr.cli.management:mccode_management

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64.0
    - setuptools_scm >=6.2
    - antlr4-python3-runtime >=4.13.2
    - antlr4-tools
  run:
    - python >={{ python_min }}
    - numpy >=2.0
    - antlr4-python3-runtime >=4.13.2
    - pooch >=1.7.0
    - confuse >=2.0.1
    - loguru >=0.7.2
    - gitpython >=3.1.43
    - git

test:
  imports:
    - mccode_antlr
  commands:
    - pip check
    - pytest tests
    - mcstas-antlr --help
    - mcxtrace-antlr --help
    - mcrun-antlr --help
    - mxrun-antlr --help
    - mccode-antlr --help
  source_files:
    - tests
  requires:
    - python {{ python_min }}
    - git
    - pytest
    - pip
    - c-compiler
    - h5py

about:
  home: https://github.com/McStasMcXtrace/mccode-antlr
  summary: McCode grammar implemented with ANTLR4
  description: |
    The mccode-antlr package provides a command-line interface to the McCode
    language parsers and translators.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/McStasMcXtrace/mccode-antlr
  dev_url: https://github.com/McStasMcXtrace/mccode-antlr

extra:
  recipe-maintainers:
    - g5t
    - willend
    - tkittel
